### ISSUE TITLE
Portworx Missing API key bug

### ISSUE THREAD

**Issue by mattokc35** [portworx/terraform-ibm-portworx-enterprise#39]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report
**What happened**:
see below 

**What you expected to happen**:
I am trying to install portworx via terraform on a VPC IKS cluster I have deployed, I am using the basic module as shown in the screenshot below. I have also specified the IBM provider and versions.tf. I was wondering, why is it telling me that I need the API key variable? I have specified the ibmcloud_api_key variable as shown in the image and also passed it in through the command line. 
**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Anything else we need to know?**:

**Environment**:
- Container Orchestrator and version: Kubernetes 1.23.12
- Cloud provider or hardware configuration: IBM Cloud
- OS (e.g. from /etc/os-release): OS X Monterrey on M1 Chip
- Kernel (e.g. `uname -a`): n/a
- Install tools:
- Others:
<img width="1147" alt="Screen Shot 2022-10-19 at 2 52 55 PM" src="https://user-images.githubusercontent.com/43581549/196790847-c04264ed-5952-47a2-bee3-c35a23793f6a.png">

**Comment by mattokc35** [comment]
@sudas-px

**Comment by mattokc35** [comment]
@sudas-px

**Comment by sudas-px** [comment]
@mattokc35,
Please export the IBM API Key for the IBM Provider
https://github.com/portworx/terraform-ibm-portworx-enterprise/blob/main/examples/README.md#setting-up-credentials 
Let me know if this still doesn't work

**Comment by mattokc35** [comment]
<img width="1611" alt="Screen Shot 2022-10-24 at 2 32 23 PM" src="https://user-images.githubusercontent.com/43581549/197610727-ae150e3d-fa76-448b-9706-3390dcaedfe1.png">
<img width="1603" alt="Screen Shot 2022-10-24 at 2 32 35 PM" src="https://user-images.githubusercontent.com/43581549/197610758-97271cb3-28cc-465f-a94f-4cc55dfec3e5.png">

I followed the commands and now it is saying my API key is invalid, although I just generated it a few minutes ago.

@sudas-px

**Comment by mattokc35** [comment]
Any idea why that might be happening? @sudas-px I exported IC_API_KEY variable

**Comment by mattokc35** [comment]
![Screen Shot 2022-10-24 at 5 38 19 PM](https://user-images.githubusercontent.com/43581549/197644010-e61afb1e-eed6-4a84-ae20-ed26b3962b0d.png)

Fixed the API key Error. Now it's giving me this error. @sudas-px

**Comment by mattokc35** [comment]
> 

Yeah I was able to run the `ibmcloud ks cluster config` command. I was also able to login with my api key. I am still getting the same error @sudas-px 
![Screen Shot 2022-10-25 at 9 27 52 AM](https://user-images.githubusercontent.com/43581549/197801201-856250a7-a5fd-4d5a-971b-babdd66e77cb.png)

**Comment by mattokc35** [comment]
@sudas-px yes it is in the default resource group. This is a VPC Gen2 IKS Cluster

**Comment by sudas-px** [comment]
@mattokc35 I believe this issue has something to do with the IBM Catalog on IBM Cloud.
<img width="1504" alt="Screenshot 2022-10-27 at 6 01 23 PM" src="https://user-images.githubusercontent.com/109576118/198284936-1f9588c0-04b2-4dca-959f-10aae842fe0a.png">

Do you mind heading over to https://cloud.ibm.com/catalog/services/portworx-enterprise and try to install Portworx-Enterprise on this same cluster?
Please let me know if this works?

**Comment by mattokc35** [comment]
![Screen Shot 2022-10-28 at 10 39 34 AM](https://user-images.githubusercontent.com/43581549/198677798-f711154e-c508-4f5e-a9b2-fb6798b23999.png)

**Comment by mattokc35** [comment]
@sudas-px I am getting this error

**Comment by sudas-px** [comment]
@mattokc35 
I understand now, you're using a service id, if I am right.
`Service Id's` are **not** supported in Portworx Enterprise Installation as of now.
You will have to use a user account with the following permissions and then generate an API Key for the Terraform Module to work.
**Minimum required permissions:**
- Administrator and VirtualServerConsoleAdmin for the VPC service.
- Manager and Administrator for the IBM Cloud Container Registry service.
- Operator and Manager for the Kubernetes service.

**Comment by mattokc35** [comment]
![Screen Shot 2022-10-28 at 10 51 00 AM](https://user-images.githubusercontent.com/43581549/198685193-e9a35dff-e635-4a11-a4f0-993b15ebe69e.png)

So here was an instance where I thought i successfully installed portworx using terraform. But upon further investigation, I realized that the Portworx instance is not connected to my VPC cluster, or any VPC cluster. It seems like it is just provisioing and not installing on any cluster, is the reason above you stated a possible reason why? @sudas-px

**Comment by sudas-px** [comment]
Yes @mattokc35, while using a `service id`, there are certain restrictions which is why the above Portworx Resource Instance is not able to associate itself with the IKS Cluster.
